title: Church Evolution Laboratory
logo: /assets/img/CEL.png
description: NYU Department of Biology, New York City, USA
show_downloads: false
google_analytics:
github:
  is_project_page: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links